const BASE=[
{name:'Roman Reigns',cha:96,str:96,stk:94,tec:86,agi:82,iq:95,finisher:'SPEAR'},{name:'Cody Rhodes',cha:94,str:86,stk:91,tec:92,agi:88,iq:94,finisher:'CROSS RHODES'},{name:'Rhea Ripley',cha:93,str:94,stk:91,tec:86,agi:84,iq:90,finisher:'RIPTIDE'},{name:'CM Punk',cha:98,str:80,stk:89,tec:95,agi:83,iq:97,finisher:'GO TO SLEEP'},{name:'IYO SKY',cha:84,str:75,stk:84,tec:92,agi:98,iq:91,finisher:'OVER THE MOONSAULT'},{name:'Seth Rollins',cha:95,str:84,stk:92,tec:93,agi:94,iq:92,finisher:'CURB STOMP'},{name:'Becky Lynch',cha:96,str:82,stk:91,tec:94,agi:87,iq:95,finisher:'MANHANDLE SLAM'},{name:'Randy Orton',cha:92,str:91,stk:93,tec:91,agi:82,iq:96,finisher:'RKO'},{name:'Bianca Belair',cha:91,str:97,stk:88,tec:85,agi:94,iq:87,finisher:'K.O.D.'},{name:'Gunther',cha:88,str:98,stk:99,tec:91,agi:75,iq:93,finisher:'POWERBOMB'},{name:'Sami Zayn',cha:94,str:82,stk:90,tec:91,agi:88,iq:92,finisher:'HELLUVA KICK'},{name:'Charlotte Flair',cha:95,str:88,stk:87,tec:96,agi:90,iq:93,finisher:'FIGURE EIGHT'}];
const KEYS=[['str','Strength'],['stk','Strike'],['tec','Technique'],['agi','Agility'],['cha','Charisma'],['iq','Ring IQ']];let save=JSON.parse(localStorage.getItem('wweSuperstarsSave')||'null'),state={};const app=document.querySelector('#app');
function persist(){localStorage.setItem('wweSuperstarsSave',JSON.stringify(save))}function statsAt(w,lvl){let m=1+(lvl-1)*.025;return Object.fromEntries(KEYS.map(([k])=>[k,Math.round(w[k]*m)]))}function hpOf(w,lvl){let s=statsAt(w,lvl);return Math.round(KEYS.reduce((a,[k])=>a+s[k],0)/6*3.4)}function level(n){return save?.roster?.[n]||0}
function artFile(name){return name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'.png'}
function card(w,l=1,c=''){let s=statsAt(w,l);let file=artFile(w.name);let art='<img class="cardart" src="assets/superstars/'+file+'" alt="'+w.name+'" onerror="this.onerror=null;this.outerHTML=\'<div class=&quot;sil&quot;></div>\'">';return '<div class="card '+c+'">'+art+'<div class="corner levelcorner"><small>LVL</small><b>'+l+'</b></div><div class="corner hpcorner"><small>HP</small><b>'+hpOf(w,l)+'</b></div><div class="name">'+w.name+'</div><div class="stats sixstats"><span class="stat-str">STR <b>'+s.str+'</b></span><span class="stat-stk">STK <b>'+s.stk+'</b></span><span class="stat-tec">TEC <b>'+s.tec+'</b></span><span class="stat-agi">AGI <b>'+s.agi+'</b></span><span class="stat-cha">CHA <b>'+s.cha+'</b></span><span class="stat-iq">IQ <b>'+s.iq+'</b></span></div></div>';}function shell(x,c=''){app.innerHTML=`<section class="screen ${c}">${x}</section>`}
function logo(){return '<img class="game-logo" src="assets/wwe-superstars-logo.webp" alt="WWE Superstars">'}
function start(){if(save)return home();shell(`<div class="startscreen"><div class="startglow"></div>${logo()}<div class="startcopy"><div class="kicker">BUILD YOUR ROSTER · BECOME UNSTOPPABLE</div><button class="btn startbtn" onclick="welcome()">START GAME</button></div></div>`,'start')}
function welcome(){let p=[...BASE].sort(()=>Math.random()-.5).slice(0,5);state.picks=p;state.reveal=0;welcomeReveal()}
function welcomeReveal(){let i=state.reveal,w=state.picks[i],last=i===state.picks.length-1;shell(`<div class="topbar onboardingbar"><span>WELCOME PACK</span><span>${i+1} / 5</span></div><div class="welcome-reveal"><div class="kicker">YOUR STARTING ROSTER</div><div class="reveal-stage">${card(w,1,'reveal-card')}</div><div class="reveal-name">${w.name}</div><div class="reveal-progress">${state.picks.map((_,n)=>'<i class="'+(n<=i?'on':'')+'"></i>').join('')}</div><button class="btn" onclick="${last?'claimWelcome()':'nextWelcome()'}">${last?'CLAIM YOUR ROSTER':'REVEAL NEXT SUPERSTAR'}</button></div>`,'onboarding')}
function nextWelcome(){state.reveal++;welcomeReveal()}
function claimWelcome(){save={roster:{},wins:0,losses:0};state.picks.forEach(x=>save.roster[x.name]=1);persist();home()}
function home(){shell(`<div class="topbar"><span>WWE SUPERSTARS</span><span>${save.wins}W · ${save.losses}L</span></div><div class="home-logo">${logo()}</div><div class="hero homehero"><div class="mode"><div class="kicker">PLAY NOW</div><h2>EXHIBITION</h2><p>Choose a Superstar. Face a random opponent. Win a reward card.</p></div><button class="btn" onclick="selectFighter()">FIGHT</button><button class="btn secondary" onclick="collection()">MY SUPERSTARS · ${Object.keys(save.roster).length}</button></div>`)}
function collection(){let o=BASE.filter(x=>level(x.name));shell(`<div class="topbar"><button onclick="home()" style="background:none;border:0">‹ HOME</button><span>${o.length} OWNED</span></div><div class="title">My Superstars</div><div class="cards">${o.sort((a,b)=>level(b.name)-level(a.name)||hpOf(b,level(b.name))-hpOf(a,level(a.name))||a.name.localeCompare(b.name)).map(x=>card(x,level(x.name))).join('')}</div>`)}
function selectFighter(){let o=BASE.filter(x=>level(x.name));shell(`<div class="topbar"><button onclick="home()" style="background:none;border:0">‹ HOME</button><span>EXHIBITION</span></div><div class="title">Choose Superstar</div><div class="sub">Pick anyone in your collection.</div><div class="cards select">${o.map(x=>`<div onclick="begin('${x.name.replaceAll("'","\\'")}')">${card(x,level(x.name))}</div>`).join('')}</div>`)}
function begin(n){let p=BASE.find(x=>x.name===n),pool=BASE.filter(x=>x.name!==n),cpu=pool[Math.floor(Math.random()*pool.length)],pl=level(n),cl=Math.max(1,Math.round(pl*(.8+Math.random()*.35)));state.b={p,cpu,pl,cl,php:hpOf(p,pl),chp:hpOf(cpu,cl),pmax:hpOf(p,pl),cmax:hpOf(cpu,cl),avail:KEYS.map(x=>x[0]),log:'Choose your attack.'};battle()}
const ATTACK_ICONS={str:'strength-icon.png',stk:'strike-icon.png',tec:'technical-icon.png',agi:'agility-icon.png',cha:'charisma-icon.png',iq:'ring-iq-icon.png'};
function battle(){let b=state.b,ps=statsAt(b.p,b.pl),choices=[...b.avail].sort(()=>Math.random()-.5).slice(0,Math.min(3,b.avail.length));shell(`<div class="topbar"><span>EXHIBITION</span><span>LIVE</span></div><div class="versus">${card(b.p,b.pl)}<div class="vs">VS</div>${card(b.cpu,b.cl)}</div><div class="hpbox"><div class="hphead"><span>${b.p.name}</span><span>${b.php}/${b.pmax}</span></div><div class="hpbar"><div class="hpfill" style="width:${Math.max(0,b.php/b.pmax*100)}%"></div></div></div><div class="hpbox"><div class="hphead"><span>${b.cpu.name}</span><span>${b.chp}/${b.cmax}</span></div><div class="hpbar"><div class="hpfill" style="width:${Math.max(0,b.chp/b.cmax*100)}%"></div></div></div><div class="log">${b.log}</div><div class="chooser"><h3>CHOOSE YOUR ATTACK</h3><div class="attacks">${choices.map(k=>`<button class="attack" onclick="attack('${k}')"><img class="attackicon" src="assets/${ATTACK_ICONS[k]}" alt=""><b>${ps[k]}</b></button>`).join('')}</div></div>`,'battle')}
function attack(pk){let b=state.b,ps=statsAt(b.p,b.pl),cs=statsAt(b.cpu,b.cl),ck=b.avail[Math.floor(Math.random()*b.avail.length)];b.chp-=ps[pk];b.php-=cs[ck];b.avail=b.avail.filter(x=>x!==pk&&x!==ck);if(!b.avail.length)b.avail=KEYS.map(x=>x[0]);b.log=`${KEYS.find(x=>x[0]===pk)[1]} ${ps[pk]} DAMAGE · ${b.cpu.name.toUpperCase()} ANSWERS WITH ${KEYS.find(x=>x[0]===ck)[1].toUpperCase()} ${cs[ck]}`;if(b.php<=0||b.chp<=0){let win=b.php<=0&&b.chp<=0?ps[pk]>=cs[ck]:b.chp<=0;return setTimeout(()=>finish(win),350)}battle()}
function finish(win){let b=state.b;if(win)save.wins++;else save.losses++;persist();let w=win?b.p:b.cpu;shell(`<div class="hero finish"><div class="kicker">${win?'YOU WIN':'DEFEAT'}</div><div class="big">${w.finisher}</div><div class="sub" style="margin-top:14px">${w.name} hits the finisher!</div><div class="count">1 · 2 · 3</div>${win?'<button class="btn" onclick="rewardPack()">Claim Reward</button>':'<button class="btn secondary" onclick="home()">Return Home</button>'}</div>`)}
function rewardPack(){shell(`<div class="hero finish"><div class="kicker">MATCH REWARD</div><div class="title">Victory Pack</div><div class="pack" onclick="openReward()">WWE<br>SUPERSTARS</div><div class="sub">Tap the pack to reveal your Superstar.</div></div>`,'reward')}
function openReward(){let w=BASE[Math.floor(Math.random()*BASE.length)],old=level(w.name),neu=old+1;save.roster[w.name]=neu;persist();shell(`<div class="hero finish"><div class="kicker">${old?'DUPLICATE ABSORBED':'NEW SUPERSTAR!'}</div>${card(w,neu,'flash')}<div class="title">${old?`LV. ${old} → LV. ${neu}`:'UNLOCKED'}</div><div class="sub">${old?'Your existing card is permanently stronger.':'Added to your WWE Superstars collection.'}</div><button class="btn" onclick="home()">Continue</button></div>`,'reward')}start();