const BASE=[
{name:'Roman Reigns',str:96,stk:94,tec:86,agi:82,iq:95,finisher:'SPEAR'},{name:'Cody Rhodes',str:86,stk:91,tec:92,agi:88,iq:94,finisher:'CROSS RHODES'},{name:'Rhea Ripley',str:94,stk:91,tec:86,agi:84,iq:90,finisher:'RIPTIDE'},{name:'CM Punk',str:80,stk:89,tec:95,agi:83,iq:97,finisher:'GO TO SLEEP'},{name:'IYO SKY',str:75,stk:84,tec:92,agi:98,iq:91,finisher:'OVER THE MOONSAULT'},{name:'Seth Rollins',str:84,stk:92,tec:93,agi:94,iq:92,finisher:'CURB STOMP'},{name:'Becky Lynch',str:82,stk:91,tec:94,agi:87,iq:95,finisher:'MANHANDLE SLAM'},{name:'Randy Orton',str:91,stk:93,tec:91,agi:82,iq:96,finisher:'RKO'},{name:'Bianca Belair',str:97,stk:88,tec:85,agi:94,iq:87,finisher:'K.O.D.'},{name:'Gunther',str:98,stk:99,tec:91,agi:75,iq:93,finisher:'POWERBOMB'},{name:'Sami Zayn',str:82,stk:90,tec:91,agi:88,iq:92,finisher:'HELLUVA KICK'},{name:'Charlotte Flair',str:88,stk:87,tec:96,agi:90,iq:93,finisher:'FIGURE EIGHT'}];
const KEYS=[['str','Strength'],['stk','Strike'],['tec','Technique'],['agi','Agility'],['iq','Ring IQ']];let save=JSON.parse(localStorage.getItem('wweSuperstarsSave')||'null'),state={};const app=document.querySelector('#app');
function persist(){localStorage.setItem('wweSuperstarsSave',JSON.stringify(save))}function statsAt(w,lvl){let m=1+(lvl-1)*.025;return Object.fromEntries(KEYS.map(([k])=>[k,Math.round(w[k]*m)]))}function hpOf(w,lvl){let s=statsAt(w,lvl);return Math.round(KEYS.reduce((a,[k])=>a+s[k],0)/5*3.4)}function level(n){return save?.roster?.[n]||0}
function card(w,l=1,c=''){let s=statsAt(w,l),art=w.name==='Roman Reigns'?\`<img class="cardart" src="assets/superstars/roman-reigns.png" alt="">\`:\`<div class="sil"></div>\`;return \`<div class="card ${c}">${art}<div class="cardinfo"><div class="name">${w.name}</div><div class="meta"><span>LEVEL <b>${l}</b></span><span>HP <b>${hpOf(w,l)}</b></span></div><div class="stats"><span><small>STRENGTH</small><b>${s.str}</b></span><span><small>STRIKE</small><b>${s.stk}</b></span><span><small>TECHNIQUE</small><b>${s.tec}</b></span><span><small>AGILITY</small><b>${s.agi}</b></span><span><small>RING IQ</small><b>${s.iq}</b></span></div></div></div>\`}function shell(x,c=''){app.innerHTML=`<section class="screen ${c}">${x}</section>`}
function start(){if(save)return home();shell(`<div class="hero"><div class="kicker">A NEW COLLECTION BEGINS</div><div class="brand">WWE<span>SUPERSTARS</span></div><div class="panel"><div class="title">Welcome</div><div class="sub">Build your roster. Win matches. Pull duplicates. Make your Superstars stronger forever.</div><button class="btn" onclick="welcome()">Open Welcome Pack</button></div></div>`)}
function welcome(){let p=[...BASE].sort(()=>Math.random()-.5).slice(0,5);state.picks=p;shell(`<div class="topbar"><span>WELCOME PACK</span><span>5 SUPERSTARS</span></div><div class="hero welcome"><div class="kicker">YOUR STARTING ROSTER</div><div class="title" style="text-align:center">Meet Your Superstars</div><div class="cards">${p.map(x=>card(x)).join('')}</div><button class="btn" onclick="claimWelcome()">Enter WWE Superstars</button></div>`)}function claimWelcome(){save={roster:{},wins:0,losses:0};state.picks.forEach(x=>save.roster[x.name]=1);persist();home()}
function home(){shell(`<div class="topbar"><span>WWE SUPERSTARS</span><span>${save.wins}W · ${save.losses}L</span></div><div class="brand" style="font-size:58px">WWE<span>SUPERSTARS</span></div><div class="hero"><div class="mode"><div class="kicker" style="text-align:left;color:#ffd6e6">PLAY NOW</div><h2>EXHIBITION</h2><p>Choose a Superstar. Face a random opponent. Win a reward card.</p></div><button class="btn" onclick="selectFighter()">Fight</button><button class="btn secondary" onclick="collection()">My Superstars · ${Object.keys(save.roster).length}</button></div>`)}
function collection(){let o=BASE.filter(x=>level(x.name));shell(`<div class="topbar"><button onclick="home()" style="background:none;border:0">‹ HOME</button><span>${o.length} OWNED</span></div><div class="title">My Superstars</div><div class="cards">${o.sort((a,b)=>level(b.name)-level(a.name)).map(x=>card(x,level(x.name))).join('')}</div>`)}
function selectFighter(){let o=BASE.filter(x=>level(x.name));shell(`<div class="topbar"><button onclick="home()" style="background:none;border:0">‹ HOME</button><span>EXHIBITION</span></div><div class="title">Choose Superstar</div><div class="sub">Pick anyone in your collection.</div><div class="cards select">${o.map(x=>`<div onclick="begin('${x.name.replaceAll("'","\\'")}')">${card(x,level(x.name))}</div>`).join('')}</div>`)}
function begin(n){let p=BASE.find(x=>x.name===n),pool=BASE.filter(x=>x.name!==n),cpu=pool[Math.floor(Math.random()*pool.length)],pl=level(n),cl=Math.max(1,Math.round(pl*(.8+Math.random()*.35)));state.b={p,cpu,pl,cl,php:hpOf(p,pl),chp:hpOf(cpu,cl),pmax:hpOf(p,pl),cmax:hpOf(cpu,cl),avail:KEYS.map(x=>x[0]),log:'Choose your attack.'};battle()}
function battle(){let b=state.b,ps=statsAt(b.p,b.pl),choices=[...b.avail].sort(()=>Math.random()-.5).slice(0,Math.min(3,b.avail.length));shell(`<div class="topbar"><span>EXHIBITION</span><span>LIVE</span></div><div class="versus">${card(b.p,b.pl)}<div class="vs">VS</div>${card(b.cpu,b.cl)}</div><div class="hpbox"><div class="hphead"><span>${b.p.name}</span><span>${b.php}/${b.pmax}</span></div><div class="hpbar"><div class="hpfill" style="width:${Math.max(0,b.php/b.pmax*100)}%"></div></div></div><div class="hpbox"><div class="hphead"><span>${b.cpu.name}</span><span>${b.chp}/${b.cmax}</span></div><div class="hpbar"><div class="hpfill" style="width:${Math.max(0,b.chp/b.cmax*100)}%"></div></div></div><div class="log">${b.log}</div><div class="chooser"><h3>CHOOSE YOUR ATTACK</h3><div class="attacks">${choices.map(k=>`<button class="attack" onclick="attack('${k}')">${KEYS.find(x=>x[0]===k)[1]}<b>${ps[k]}</b></button>`).join('')}</div></div>`,'battle')}
function attack(pk){let b=state.b,ps=statsAt(b.p,b.pl),cs=statsAt(b.cpu,b.cl),ck=b.avail[Math.floor(Math.random()*b.avail.length)];b.chp-=ps[pk];b.php-=cs[ck];b.avail=b.avail.filter(x=>x!==pk&&x!==ck);if(!b.avail.length)b.avail=KEYS.map(x=>x[0]);b.log=`${KEYS.find(x=>x[0]===pk)[1]} ${ps[pk]} DAMAGE · ${b.cpu.name.toUpperCase()} ANSWERS WITH ${KEYS.find(x=>x[0]===ck)[1].toUpperCase()} ${cs[ck]}`;if(b.php<=0||b.chp<=0){let win=b.php<=0&&b.chp<=0?ps[pk]>=cs[ck]:b.chp<=0;return setTimeout(()=>finish(win),350)}battle()}
function finish(win){let b=state.b;if(win)save.wins++;else save.losses++;persist();let w=win?b.p:b.cpu;shell(`<div class="hero finish"><div class="kicker">${win?'YOU WIN':'DEFEAT'}</div><div class="big">${w.finisher}</div><div class="sub" style="margin-top:14px">${w.name} hits the finisher!</div><div class="count">1 · 2 · 3</div>${win?'<button class="btn" onclick="rewardPack()">Claim Reward</button>':'<button class="btn secondary" onclick="home()">Return Home</button>'}</div>`)}
function rewardPack(){shell(`<div class="hero finish"><div class="kicker">MATCH REWARD</div><div class="title">Victory Pack</div><div class="pack" onclick="openReward()">WWE<br>SUPERSTARS</div><div class="sub">Tap the pack to reveal your Superstar.</div></div>`,'reward')}
function openReward(){let w=BASE[Math.floor(Math.random()*BASE.length)],old=level(w.name),neu=old+1;save.roster[w.name]=neu;persist();shell(`<div class="hero finish"><div class="kicker">${old?'DUPLICATE ABSORBED':'NEW SUPERSTAR!'}</div>${card(w,neu,'flash')}<div class="title">${old?`LV. ${old} → LV. ${neu}`:'UNLOCKED'}</div><div class="sub">${old?'Your existing card is permanently stronger.':'Added to your WWE Superstars collection.'}</div><button class="btn" onclick="home()">Continue</button></div>`,'reward')}start();