const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const origin='http://127.0.0.1:8765/';
 await page.goto(origin,{waitUntil:'domcontentloaded'});
 await page.getByText('OPEN WELCOME PACK').click();
 for(let i=0;i<4;i++)await page.getByText('REVEAL NEXT').click();
 await page.getByText('ENTER WWE SUPERSTARS').click();
 assert(await page.locator('.home-v2').count(),'home should render after onboarding');
 await page.evaluate(()=>exhibitionMenu());
 assert(await page.getByText('CHOOSE MATCH TYPE').count(),'exhibition menu should render');
 await page.evaluate(()=>selectMultiFighter(4));
 assert.equal(await page.locator('.exhibition-filters select').count(),3);
 await page.evaluate(()=>{save.roster['Rhea Ripley']=1;save.roster['Roman Reigns']=1;persist();pickMultiFighter()});
 await page.locator('.exhibition-filters select').first().selectOption('Female');
 assert((await page.locator('.exhibition-roster > div:visible').count())>0,'female filter should have matches');
 await page.locator('.exhibition-filters select').first().selectOption('');
 await page.locator('.exhibition-roster > div:visible').first().click();
 assert(await page.getByText('Choose Superstar 2 of 4').count(),'second pick should render');
 await page.evaluate(()=>selectFighter());
 assert.equal(await page.locator('.exhibition-filters select').count(),3);
 await page.evaluate(()=>selectTagFighter());
 assert.equal(await page.locator('.exhibition-filters select').count(),3);
 await page.evaluate(()=>begin('Roman Reigns'));
 assert(await page.locator('.battle').count()||await page.locator('.chooser').count(),'battle should render');
 await page.evaluate(()=>attack(state.b.hand[0]));
 assert(errors.length===0,'battle turn should not throw');
 await page.evaluate(()=>collection());
 assert(await page.locator('.collection-gallery').count(),'collection should render');
 await page.evaluate(()=>shop());
 assert(await page.locator('.shop-screen').count(),'shop should render');
 await page.evaluate(()=>wweLive());
 assert(await page.locator('.live-screen').count(),'live should render');
 await page.reload({waitUntil:'domcontentloaded'});
 assert(await page.locator('.home-v2').count(),'save should survive reload');
 await page.evaluate(()=>localStorage.setItem('wweSuperstarsSave','{invalid-json'));
 await page.reload({waitUntil:'domcontentloaded'});
 assert(await page.getByText('OPEN WELCOME PACK').count(),'corrupt save must not crash boot');
 assert.equal(await page.evaluate(()=>localStorage.getItem('wweSuperstarsSave_corrupt_backup')),'{invalid-json','corrupt save should be backed up');
 assert.deepEqual(errors,[],'uncaught browser errors');
 console.log('PASS browser smoke: onboarding, home, filters, multi pick, singles, tag, battle turn, collection, shop, live, save reload, corrupt-save recovery');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
