const fs=require('node:fs'),vm=require('node:vm');
let seed=202610061; const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
const app={innerHTML:''},ctx=vm.createContext({console,Math:Object.assign(Object.create(Math),{random:rnd}),localStorage:{getItem:()=>null,setItem(){}},document:{querySelector:()=>app},setTimeout:fn=>fn(),clearInterval(){},setInterval:()=>1,window:{},URL,Image:function(){}});
let src=fs.readFileSync('app.js','utf8').replace(/start\(\);setTimeout\(\(\)=>\{loadFinisherMedia\(\);preloadRosterInBackground\(\)\},1500\);\s*$/,'');
vm.runInContext(src+`\nglobalThis.g={BASE,KEYS,ACTIONS,ROAD_MODS,statsAt,hpOf,actionBy,actionValue,chooseCard,initActionDecks,battle,attack,roadNode,get b(){return state.b},set b(v){state.b=v},setCPU(fn){cpuChoice=fn},resetCPU(){cpuChoice=this.cpuChoice}};finish=win=>{state.b.result=win};preloadMatchMedia=()=>{};loadFinisherMedia=()=>Promise.resolve({});`,ctx);
const g=ctx.g,keys=g.KEYS.map(x=>x[0]);
function rank(b,stats,side,hand){let left=[...hand],out=[];while(left.length){let best=g.chooseCard(b,stats,side,left);out.push(best);left=left.filter(x=>x!==best)}return out}
const profiles={optimal:[1,0,0],decent:[.80,.15,.05],average:[.55,.25,.20],poor:[1/3,1/3,1/3]};
function pick(profile,b,stats,side,hand){let r=rank(b,stats,side,hand),p=profiles[profile],x=rnd(),i=x<p[0]?0:x<p[0]+p[1]?1:2;return r[Math.min(i,r.length-1)]}
function makeMatch(p,node){let lvl=node.band,cpu=node.cpu,pmax=g.hpOf(p,lvl),cmax=g.hpOf(cpu,lvl);if(node.mod.id==='iron'){pmax=Math.round(pmax*1.25);cmax=Math.round(cmax*1.25)}if(node.mod.id==='glass'){pmax=Math.round(pmax*.7);cmax=Math.round(cmax*.7)}let php=pmax,chp=cmax;if(node.mod.id==='opening'){php=Math.round(pmax*.75);chp=Math.round(cmax*.75)}return {p,cpu,pl:lvl,cl:lvl,php,chp,pmax,cmax,avail:[...node.pool],road:true,node,log:'SIM'} }
function one(profile,p,node){let b=makeMatch(p,node);g.b=b;g.battle();let turns=0;while(b.result===undefined&&turns<30){let ps=g.statsAt(p,b.pl),pk=pick(profile,b,ps,'p',b.hand);g.attack(pk);turns++}return {win:!!b.result,turns,timeout:b.result===undefined}}
let out={version:src.match(/APP_VERSION='([^']+)'/)[1],seed:202610061,runsPerProfile:100,matchesPerRun:50,profiles:{}};
for(const profile of Object.keys(profiles)){let s={matches:0,wins:0,losses:0,turns:0,timeouts:0,maxNodeSum:0,finalNodeSum:0,reached25:0,reached50:0,reached75:0,reached100:0,backsteps:0,byPosition:{}};for(let run=0;run<out.runsPerProfile;run++){let nodeNo=1,maxNode=1;for(let m=0;m<out.matchesPerRun;m++){let node=g.roadNode(nodeNo),eligible=g.BASE.filter(w=>!node.eligibleTag||(w.tags||[]).includes(node.eligibleTag)),p=eligible[Math.floor(rnd()*eligible.length)],r=one(profile,p,node);s.matches++;s.turns+=r.turns;s.timeouts+=+r.timeout;if(r.win){s.wins++;nodeNo++}else{s.losses++;let before=nodeNo;nodeNo=Math.max(1,nodeNo-1);if(nodeNo<before)s.backsteps++}maxNode=Math.max(maxNode,nodeNo);let q=s.byPosition[p.position]||(s.byPosition[p.position]={matches:0,wins:0});q.matches++;q.wins+=+r.win} s.maxNodeSum+=maxNode;s.finalNodeSum+=nodeNo;s.reached25+=+(maxNode>=25);s.reached50+=+(maxNode>=50);s.reached75+=+(maxNode>=75);s.reached100+=+(maxNode>=100)}
 s.winRate=s.wins/s.matches;s.meanTurns=s.turns/s.matches;s.meanMaxNode=s.maxNodeSum/out.runsPerProfile;s.meanFinalNode=s.finalNodeSum/out.runsPerProfile;for(let k of ['reached25','reached50','reached75','reached100'])s[k]/=out.runsPerProfile;out.profiles[profile]=s;console.log(profile,s.winRate,s.meanMaxNode,s.meanFinalNode)}
fs.writeFileSync('tools/player-experience-results.json',JSON.stringify(out,null,2)+'\n');

