const fs=require('node:fs'),vm=require('node:vm');
let seed=202610061; const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296};
const app={innerHTML:''},ctx=vm.createContext({console,Math:Object.assign(Object.create(Math),{random:rnd}),localStorage:{getItem:()=>null,setItem(){}},document:{querySelector:()=>app},setTimeout:fn=>fn(),clearInterval(){},setInterval:()=>1,window:{},URL,Image:function(){}});
let src=fs.readFileSync('app.js','utf8').replace(/start\(\);setTimeout\(\(\)=>\{loadFinisherMedia\(\);preloadRosterInBackground\(\)\},1500\);\s*$/,'');
vm.runInContext(src+`\nglobalThis.g={BASE,KEYS,ACTIONS,ROAD_MODS,statsAt,hpOf,actionBy,actionValue,chooseCard,initActionDecks,battle,attack,roadNode,get b(){return state.b},set b(v){state.b=v},setCPU(fn){cpuChoice=fn},resetCPU(){cpuChoice=this.cpuChoice}};finish=win=>{state.b.result=win};preloadMatchMedia=()=>{};loadFinisherMedia=()=>Promise.resolve({});`,ctx);
const g=ctx.g,keys=g.KEYS.map(x=>x[0]);
function rank(b,stats,side,hand){let left=[...hand],out=[];while(left.length){let best=g.chooseCard(b,stats,side,left);out.push(best);left=left.filter(x=>x!==best)}return out}
const profiles={optimal:[1,0,0],decent:[.80,.15,.05],average:[.55,.25,.20],poor:[1/3,1/3,1/3]};
function pick(profile,b,stats,side,hand){let r=rank(b,stats,side,hand),p=profiles[profile],x=rnd(),i=x<p[0]?0:x<p[0]+p[1]?1:2;return r[Math.min(i,r.length-1)]}
function makeMatch(p,node,playerLevel){let lvl=node.band,cpu=node.cpu,pmax=g.hpOf(p,playerLevel),cmax=g.hpOf(cpu,lvl);if(node.mod.id==='iron'){pmax=Math.round(pmax*1.25);cmax=Math.round(cmax*1.25)}if(node.mod.id==='glass'){pmax=Math.round(pmax*.7);cmax=Math.round(cmax*.7)}let php=pmax,chp=cmax;if(node.mod.id==='opening'){php=Math.round(pmax*.75);chp=Math.round(cmax*.75)}return {p,cpu,pl:playerLevel,cl:lvl,php,chp,pmax,cmax,avail:[...node.pool],road:true,node,log:'SIM'} }
function one(profile,p,node,playerLevel){let b=makeMatch(p,node,playerLevel);g.b=b;g.battle();let turns=0;while(b.result===undefined&&turns<30){let ps=g.statsAt(p,b.pl),pk=pick(profile,b,ps,'p',b.hand);g.attack(pk);turns++}return {win:!!b.result,turns,timeout:b.result===undefined}}
let out={version:src.match(/APP_VERSION='([^']+)'/)[1],seed:202610061,runsPerScenario:100,matchesPerRun:50,scenarios:{}};
const scenarios=[
 {id:'L1_vs_road',playerLevel:1},
 {id:'L2_vs_road',playerLevel:2},
 {id:'L3_vs_road',playerLevel:3},
 {id:'L4_vs_road',playerLevel:4}
];
for(const scenario of scenarios){out.scenarios[scenario.id]={playerLevel:scenario.playerLevel,profiles:{}};for(const profile of Object.keys(profiles)){let s={matches:0,wins:0,losses:0,turns:0,timeouts:0,maxNodeSum:0,finalNodeSum:0,reached25:0,reached50:0,backsteps:0,byRoadLevel:{}};for(let run=0;run<out.runsPerScenario;run++){let nodeNo=1,maxNode=1;for(let m=0;m<out.matchesPerRun;m++){let node=g.roadNode(nodeNo),eligible=g.BASE.filter(w=>!node.eligibleTag||(w.tags||[]).includes(node.eligibleTag)),p=eligible[Math.floor(rnd()*eligible.length)],r=one(profile,p,node,scenario.playerLevel);s.matches++;s.turns+=r.turns;s.timeouts+=+r.timeout;if(r.win){s.wins++;nodeNo++}else{s.losses++;let before=nodeNo;nodeNo=Math.max(1,nodeNo-1);if(nodeNo<before)s.backsteps++}maxNode=Math.max(maxNode,nodeNo);let q=s.byRoadLevel[node.band]||(s.byRoadLevel[node.band]={matches:0,wins:0});q.matches++;q.wins+=+r.win} s.maxNodeSum+=maxNode;s.finalNodeSum+=nodeNo;s.reached25+=+(maxNode>=25);s.reached50+=+(maxNode>=50)}
 s.winRate=s.wins/s.matches;s.meanTurns=s.turns/s.matches;s.meanMaxNode=s.maxNodeSum/out.runsPerScenario;s.meanFinalNode=s.finalNodeSum/out.runsPerScenario;s.reached25/=out.runsPerScenario;s.reached50/=out.runsPerScenario;for(const q of Object.values(s.byRoadLevel))q.winRate=q.wins/q.matches;out.scenarios[scenario.id].profiles[profile]=s;console.log(scenario.id,profile,'win',s.winRate.toFixed(4),'max',s.meanMaxNode.toFixed(2),'final',s.meanFinalNode.toFixed(2),JSON.stringify(s.byRoadLevel))}}
fs.writeFileSync('tools/player-experience-results.json',JSON.stringify(out,null,2)+'\\n');

// Daily loop audit: five Gauntlet wins level the featured Superstar, then Road, then Exhibition fallback.
function gauntletNode(stage,cpu){let mods=['normal','noStat','specialist','comeback','random'],mod=g.ROAD_MODS.find(x=>x.id===mods[stage-1])||g.ROAD_MODS[0],pool=[...keys],blocked=null;if(mod.id==='noStat'){blocked=pool[stage%pool.length];pool=pool.filter(x=>x!==blocked)}if(mod.id==='specialist')pool=pool.slice(0,4);return {cpu,band:1,mod,pool,blocked}}
function gauntletMatch(profile,p,cpu,stage,level){let node=gauntletNode(stage,cpu),b=makeMatch(p,node,level);b.cl=level;b.cmax=g.hpOf(cpu,level);b.chp=b.cmax;b.gauntlet=true;b.gauntletStage=stage;g.b=b;g.battle();let turns=0;while(b.result===undefined&&turns<30){let ps=g.statsAt(p,b.pl),pk=pick(profile,b,ps,'p',b.hand);g.attack(pk);turns++}return !!b.result}
let daily={runsPerProfile:100,profiles:{}};
for(const profile of Object.keys(profiles)){let d={days:0,gauntletMatches:0,gauntletWins:0,gauntletCompletions:0,roadMatches:0,roadWins:0,exhibitionNeeded:0,finalLevelSum:0,maxRoadNodeSum:0};for(let run=0;run<daily.runsPerProfile;run++){let p=g.BASE[Math.floor(rnd()*g.BASE.length)],cpu=p,level=1,wins=0,attempts=0;while(wins<5&&attempts<50){attempts++;let stage=wins+1;if(gauntletMatch(profile,p,cpu,stage,level)){wins++;level++}}d.days++;d.gauntletMatches+=attempts;d.gauntletWins+=wins;d.gauntletCompletions+=+(wins===5);let nodeNo=1,maxNode=1;for(let m=0;m<50;m++){let node=g.roadNode(nodeNo),r=one(profile,p,node,level);d.roadMatches++;if(r.win){d.roadWins++;nodeNo++}else nodeNo=Math.max(1,nodeNo-1);maxNode=Math.max(maxNode,nodeNo)}d.exhibitionNeeded+=+(maxNode<25);d.finalLevelSum+=level;d.maxRoadNodeSum+=maxNode}d.gauntletWinRate=d.gauntletWins/d.gauntletMatches;d.gauntletCompletionRate=d.gauntletCompletions/d.days;d.avgGauntletMatches=d.gauntletMatches/d.days;d.roadWinRate=d.roadWins/d.roadMatches;d.exhibitionNeedRate=d.exhibitionNeeded/d.days;d.avgFinalLevel=d.finalLevelSum/d.days;d.avgMaxRoadNode=d.maxRoadNodeSum/d.days;daily.profiles[profile]=d;console.log('DAILY',profile,JSON.stringify(d))}
out.dailyLoop=daily;fs.writeFileSync('tools/player-experience-results.json',JSON.stringify(out,null,2)+'\\n');

// Exhibition economy audit: unlimited wins, random reward from the actual BASE roster.
// Geometric model measures the grind required to target a specific Superstar duplicate.
const rosterSize=g.BASE.length;
const targetP=1/rosterSize;
function expectedWinsForCopies(copies){return copies/targetP}
function winsForChance(copies,chance){let n=0,p=0;while(p<chance&&n<100000){n++;let q=1-targetP,p0=Math.pow(q,n),sum=p0,term=p0;for(let k=1;k<copies;k++){term*=((n-k+1)/k)*(targetP/q);sum+=term}p=1-sum}return n}
out.exhibitionEconomy={rosterSize,targetRewardProbability:targetP,expectedWinsPerTargetCopy:1/targetP,targets:{one:{expectedWins:expectedWinsForCopies(1),winsFor50pct:winsForChance(1,.5),winsFor90pct:winsForChance(1,.9)},five:{expectedWins:expectedWinsForCopies(5),winsFor50pct:winsForChance(5,.5),winsFor90pct:winsForChance(5,.9)}}};
console.log('EXHIBITION_ECONOMY',JSON.stringify(out.exhibitionEconomy));
fs.writeFileSync('tools/player-experience-results.json',JSON.stringify(out,null,2)+'\\n');

// Infinite Road wall audit: measure where fixed player levels stall on the actual endless Road curve.
let infiniteRoad={runsPerLevelProfile:50,maxMatches:1000,levels:{}};
for(let playerLevel=1;playerLevel<=10;playerLevel++){let L=infiniteRoad.levels[playerLevel]={};for(const profile of Object.keys(profiles)){let maxSum=0,finalSum=0,peak=0,roadBandAtWall={},stalled=0;for(let run=0;run<infiniteRoad.runsPerLevelProfile;run++){let p=g.BASE[Math.floor(rnd()*g.BASE.length)],nodeNo=1,maxNode=1,noNewPeak=0;for(let m=0;m<infiniteRoad.maxMatches;m++){let node=g.roadNode(nodeNo),r=one(profile,p,node,playerLevel);if(r.win)nodeNo++;else nodeNo=Math.max(1,nodeNo-1);if(nodeNo>maxNode){maxNode=nodeNo;noNewPeak=0}else noNewPeak++;if(noNewPeak>=150){stalled++;break}}maxSum+=maxNode;finalSum+=nodeNo;peak=Math.max(peak,maxNode);let wb=g.roadNode(maxNode).band;roadBandAtWall[wb]=(roadBandAtWall[wb]||0)+1}L[profile]={avgMaxNode:maxSum/infiniteRoad.runsPerLevelProfile,avgFinalNode:finalSum/infiniteRoad.runsPerLevelProfile,peakNode:peak,stallRuns:stalled,wallRoadBands:roadBandAtWall};console.log('INFINITE_ROAD','L'+playerLevel,profile,JSON.stringify(L[profile]))}}
out.infiniteRoad=infiniteRoad;fs.writeFileSync('tools/player-experience-results.json',JSON.stringify(out,null,2)+'\\n');

// Long-term roster economy audit: random pulls create an uneven roster; daily Gauntlet can reorder the leaders.
let rosterEconomy={rosterSize:g.BASE.length,days:180,runs:100,exhibitionWinsPerDay:[0,5,20,50],cohorts:{}};
for(const exPerDay of rosterEconomy.exhibitionWinsPerDay){let agg={top1:0,top2:0,top3:0,spread:0,gauntletNewLeader:0,gauntletTop3Jump:0,days:0,roadWall:0};for(let run=0;run<rosterEconomy.runs;run++){let lv=Array(g.BASE.length).fill(1);for(let day=0;day<rosterEconomy.days;day++){let before=[...lv].sort((a,b)=>b-a),featured=Math.floor(rnd()*lv.length),oldRank=[...lv].sort((a,b)=>b-a).indexOf(lv[featured])+1;lv[featured]+=5;let afterG=[...lv].sort((a,b)=>b-a);if(lv[featured]===afterG[0]&&lv[featured]>before[0])agg.gauntletNewLeader++;let newRank=afterG.indexOf(lv[featured])+1;if(oldRank>3&&newRank<=3)agg.gauntletTop3Jump++;for(let e=0;e<exPerDay;e++)lv[Math.floor(rnd()*lv.length)]++;let s=[...lv].sort((a,b)=>b-a);agg.top1+=s[0];agg.top2+=s[1];agg.top3+=s[2];agg.spread+=s[0]-s[Math.floor(s.length/2)];agg.days++;let best=s[0];let approx=g.roadNode(1);let n=1;while(n<1000&&g.roadNode(n).band<best)n++;agg.roadWall+=n}}for(const k of ['top1','top2','top3','spread','roadWall'])agg[k]/=agg.days;agg.gauntletNewLeaderRate=agg.gauntletNewLeader/agg.days;agg.gauntletTop3JumpRate=agg.gauntletTop3Jump/agg.days;rosterEconomy.cohorts[exPerDay]=agg;console.log('ROSTER_ECONOMY','EX'+exPerDay,JSON.stringify(agg))}
out.rosterEconomy=rosterEconomy;fs.writeFileSync('tools/player-experience-results.json',JSON.stringify(out,null,2)+'\\n');
